import { defineConfig } from 'vitepress';
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { svelte } from '@sveltejs/vite-plugin-svelte';

const isDev = process.env.NODE_ENV === 'development';
const base = isDev ? '/' : '/qkd/';

// One sidebar row per report page `./do test` wrote into docs/tests/.
const reports = readdirSync(new URL('../tests', import.meta.url))
  .filter((f) => f.endsWith('.md') && f !== 'index.md')
  .sort()
  .map((f) => f.slice(0, -3))
  .map((name) => ({ text: name, link: `/tests/${name}` }));

export default defineConfig({
  base,
  // Jekyll skips paths starting with `_`, so GitHub Pages needs a .nojekyll.
  // Written every build because `vitepress build` clears outDir; `gh-pages -t`
  // publishes it.
  buildEnd: (cfg) => {
    writeFileSync(join(cfg.outDir, '.nojekyll'), '');
  },
  title: "qkd",
  description: "Continuous-variable quantum optics and CV-QKD simulation, with a native Rust core.",
  head: [
    // VitePress does not base-prefix head hrefs, so prepend `base` by hand.
    // Source is docs/public/icon.svg.
    ['link', { rel: 'icon', type: 'image/svg+xml', href: base + 'icon.svg' }],
  ],
  markdown: {
    // Macros are MathJax's, via markdown-it-mathjax3.
    math: {
      tex: {
        macros: {
          "\\ket": ["\\left|{#1}\\right\\rangle", 1],
          "\\bra": ["\\left\\langle{#1}\\right|", 1],
          "\\braket": ["\\left\\langle{#1}\\right\\rangle", 1]
        }
      }
    },
    lineNumbers: true
  },
  ignoreDeadLinks: [
    // /tests/ pages are generated by `./do test` and gitignored, so they are
    // absent on a fresh checkout.
    /^\/tests\//,
  ],
  themeConfig: {
    // VitePress base-prefixes themeConfig.logo but not head hrefs above, so this
    // one is site-root.
    logo: '/icon.svg',
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Getting Started', link: '/getting-started' },
      { text: 'Guide', link: '/guide/conventions' },
      { text: 'Studio', link: '/studio' },
      { text: 'Roadmap', link: '/roadmap' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting Started', link: '/getting-started' },
          { text: 'Usage by example', link: '/usage' },
          { text: 'Conventions', link: '/guide/conventions' },
          { text: 'Gaussian layer', link: '/guide/gaussian' },
          { text: 'Non-Gaussian states', link: '/guide/fock' },
          { text: 'Protocol layer', link: '/guide/link' },
          { text: 'Protocol coverage', link: '/guide/protocols' },
          { text: 'Swap & network topologies', link: '/guide/relay' },
          { text: 'Noise budget', link: '/guide/budget' },
          { text: 'Impairments', link: '/guide/impairments' },
          { text: 'Security', link: '/guide/security' },
          { text: 'Validation', link: '/guide/validation' },
          { text: 'Architecture', link: '/architecture' },
          { text: 'Status & roadmap', link: '/roadmap' },
        ]
      },
      {
        text: 'Studio',
        link: '/studio',
      },
      {
        text: 'Testing',
        items: [
          { text: 'Overview', link: '/tests/' },
          ...reports,
        ],
      },
    ],

    search: {
      provider: 'local'
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/plutoniumm/qkd' },
    ]
  },
  vite: {
    plugins: [svelte()],
    resolve: {
      alias: {
        uplot: fileURLToPath(new URL('../node_modules/uplot', import.meta.url)),
      },
    },
    // A Svelte island is imported, not rendered, during the SSR pass, so these
    // must be bundled rather than externalized as bare Node requires. No page
    // mounts one since the tutorial track was deleted; theme/SvelteIsland.vue
    // is the remaining mount point.
    ssr: {
      noExternal: ['svelte', 'uplot', 'katex'],
    },
    server: {
      port: 3000,
      // Vite 403s any Host that is not localhost. The leading dot admits every
      // subdomain, so one entry covers the reverse proxy's per-port hosts.
      // Dev only; `vitepress build` does not read this.
      allowedHosts: ['.gojira.manav.ch'],
      fs: {
        strict: false
      },
    }
  }
});
