use pyo3::prelude::*;

mod b92;
mod backend;
mod cascade;
mod click;
mod decoy;
mod discrete;
mod dmcs;
mod ekert;
mod eur;
mod flaws;
mod fock;
mod gaussian;
mod herm;
mod keyrate;
mod lp;
mod mdi;
mod numeric;
mod pairing;
mod pairs;
mod pipeline;
mod pnr;
mod postselect;
mod relay;
mod rrdps;
mod sarg;
mod sdp;
mod sixstate;
mod std;
mod threefry;
mod tlo;

/// The resolved backend: `(name, precision, device)`, e.g.
/// `("gpu", "f32", "Apple M3 Pro (Metal)")`.
#[pyfunction]
fn backend_info() -> (String, String, String) {
    let b = backend::resolve();

    (
        b.name().to_string(),
        b.precision().to_string(),
        b.device(),
    )
}

/// Whether the resolved backend carries the requested precision natively. DSP
/// asks `"f32"`; covariance and key rate ask `"f64"` and land on the CPU.
#[pyfunction]
fn supports(precision: &str) -> PyResult<bool> {
    Ok(backend::resolve().supports(backend::Precision::parse(precision)?))
}

#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
    m.add(
        "__doc__",
        "qkd native core: continuous-variable quantum optics engines.",
    )?;
    m.add("__gpu__", cfg!(feature = "gpu"))?;

    m.add_function(wrap_pyfunction!(backend_info, m)?)?;
    m.add_function(wrap_pyfunction!(supports, m)?)?;

    // Backend plumbing, deliberately not re-exported: the CPU entries arbitrate the GPU ones.
    m.add_class::<backend::SymStats>()?;
    m.add_function(wrap_pyfunction!(backend::gpu_ready, m)?)?;
    m.add_function(wrap_pyfunction!(backend::gpu_probe, m)?)?;
    m.add_function(wrap_pyfunction!(backend::gpu_empty, m)?)?;
    m.add_function(wrap_pyfunction!(backend::cpu_words, m)?)?;
    m.add_function(wrap_pyfunction!(backend::gpu_words, m)?)?;
    m.add_function(wrap_pyfunction!(backend::cpu_symbols, m)?)?;
    m.add_function(wrap_pyfunction!(backend::gpu_symbols, m)?)?;
    m.add_function(wrap_pyfunction!(backend::split_symbols, m)?)?;

    m.add_class::<gaussian::GaussianState>()?;
    m.add_class::<fock::FockState>()?;
    m.add_class::<pipeline::SimOut>()?;
    m.add_class::<click::ClickOut>()?;
    m.add_function(wrap_pyfunction!(pipeline::run_symbols, m)?)?;
    m.add_function(wrap_pyfunction!(pipeline::run_tlo, m)?)?;
    m.add_function(wrap_pyfunction!(click::run_clicks, m)?)?;
    m.add_function(wrap_pyfunction!(click::click_prob, m)?)?;
    m.add_function(wrap_pyfunction!(click::interfere, m)?)?;
    m.add_function(wrap_pyfunction!(click::jitter_split, m)?)?;
    m.add_function(wrap_pyfunction!(click::bg_raman, m)?)?;
    m.add_function(wrap_pyfunction!(click::bg_rayleigh, m)?)?;
    m.add_function(wrap_pyfunction!(click::bg_floor, m)?)?;
    m.add_function(wrap_pyfunction!(click::bg_thermal, m)?)?;
    m.add_function(wrap_pyfunction!(click::dps_source, m)?)?;
    m.add_function(wrap_pyfunction!(click::dps_counts, m)?)?;
    m.add_function(wrap_pyfunction!(click::dps_kato, m)?)?;
    m.add_function(wrap_pyfunction!(click::dps_phase, m)?)?;
    m.add_function(wrap_pyfunction!(click::dps_finite, m)?)?;
    m.add_class::<pnr::Povm>()?;
    m.add_function(wrap_pyfunction!(pnr::pnr_array, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_tes, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_confuse, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_coherent, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_distinct, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_noclick, m)?)?;
    m.add_function(wrap_pyfunction!(pnr::pnr_decoy, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::cv_rate, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::cv_bounds, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::cv_finite, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::cv_general, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::dps_rate, m)?)?;
    m.add_function(wrap_pyfunction!(keyrate::z_pe, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_bounds, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_ideal, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_gain, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_eta, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_counts, m)?)?;
    m.add_function(wrap_pyfunction!(decoy::decoy_errors, m)?)?;
    m.add_class::<discrete::BasisOut>()?;
    m.add_function(wrap_pyfunction!(discrete::bb84_rate, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::bb84_eps, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::bb84_phase, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::key_share, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::bb84_length, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::run_basis, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_rate, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_ceiling, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_visibility, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_residual, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_data, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_monitor, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::cow_finite, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::pol_contrast, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::pol_walk, m)?)?;
    m.add_function(wrap_pyfunction!(discrete::pol_error, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_states, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_moments, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_holevo, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_info, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_rate, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_region, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_honest, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_relent, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_cost, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_secure, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_noisy, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_observe, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_trusted, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_finite, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_price, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_energy, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_wchoice, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_accept, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_secpar, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_length, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_relaxed, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_weight, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_clip, m)?)?;
    m.add_function(wrap_pyfunction!(dmcs::dm_number, m)?)?;
    m.add_function(wrap_pyfunction!(herm::herm_eig, m)?)?;
    m.add_function(wrap_pyfunction!(herm::herm_residual, m)?)?;
    m.add_function(wrap_pyfunction!(herm::herm_cone, m)?)?;
    m.add_function(wrap_pyfunction!(herm::herm_split, m)?)?;
    m.add_function(wrap_pyfunction!(relay::relay_omega, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_noise, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_floor, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_least, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_rate, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_cov, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_point, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_excess, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_gauss, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_width, m)?)?;
    m.add_function(wrap_pyfunction!(relay::cvmdi_finite, m)?)?;
    m.add_function(wrap_pyfunction!(relay::mode_overlap, m)?)?;
    m.add_function(wrap_pyfunction!(relay::hom_visibility, m)?)?;
    m.add_function(wrap_pyfunction!(relay::relay_ports, m)?)?;
    m.add_function(wrap_pyfunction!(relay::relay_counts, m)?)?;
    m.add_function(wrap_pyfunction!(relay::relay_error, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_yield, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_rect, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_diag, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_y11, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_e11, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_gain, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_rate, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_deviate, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_pairs, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_faults, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_vacuum, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_single, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_phase, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_eps, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_length, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_program, m)?)?;
    m.add_function(wrap_pyfunction!(mdi::mdi_disturb, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_click, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_pairs, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_sift, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_single, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_span, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_drift, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_rate, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_ladder, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_bases, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_eps, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_observe, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_expect, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_yield, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_gamma, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_phase, m)?)?;
    m.add_function(wrap_pyfunction!(pairing::pairing_length, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_gain, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_correlated, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_error, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_rate, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_optimum, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_holevo, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_chsh, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_secpar, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_length, m)?)?;
    m.add_function(wrap_pyfunction!(pairs::pair_finite, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_settings, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_correlate, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_chsh, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_qber, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_rate, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_point, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_threshold, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_overlap, m)?)?;
    m.add_function(wrap_pyfunction!(ekert::ekert_finite, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_bell, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_eve, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_holevo, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_secret, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_rate, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_sift, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_width, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_bound, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_pooled, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_eps, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_length, m)?)?;
    m.add_function(wrap_pyfunction!(sixstate::sixstate_finite, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_overlap, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_usd, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_detect, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_ceiling, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_rate, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_tolerance, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_point, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_optimum, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_phase, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_channel, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_plain, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_limit, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_finite, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_window, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_monitor, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_derived, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_strong, m)?)?;
    m.add_function(wrap_pyfunction!(b92::b92_azuma, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_leak, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_src, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_phase, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_tag, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_gllp, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_rate, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_collective, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_simplex, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_tolerance, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_counts, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_optimum, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_above, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_tagged, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_secpar, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_split, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_length, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_finite, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_entropy, m)?)?;
    m.add_function(wrap_pyfunction!(rrdps::rrdps_polytope, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_sift, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_yield, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_gain, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_cost, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_phase, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_domain, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_rate, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_limit, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_ceiling, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_eps, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_counts, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_errors, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_length, m)?)?;
    m.add_function(wrap_pyfunction!(sarg::sarg_finite, m)?)?;
    m.add_function(wrap_pyfunction!(lp::lp_dual, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_lmi, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_gram, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_gains, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_honest, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_data, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_analytic, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_phase, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_eps, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_kato, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_interval, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_sample, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_length, m)?)?;
    m.add_function(wrap_pyfunction!(sdp::sdp_finite, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_angles, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_virtual, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_triangle, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_fidelity, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_channel, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_phase, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_direct, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_coin, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_gllp, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_tolerant, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_standard, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_azuma, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_eps, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_inverse, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_errors, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_length, m)?)?;
    m.add_function(wrap_pyfunction!(flaws::flaw_finite, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_shot, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_calib, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_estimate, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_cov, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_monitor, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_range, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_phase, m)?)?;
    m.add_function(wrap_pyfunction!(tlo::tlo_leak, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_dim, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_squash, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_tagged, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_optical, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_cost, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_cap, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_secrecy, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_epsilon, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_budget, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_thirds, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_length, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_width, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_family, m)?)?;
    m.add_function(wrap_pyfunction!(postselect::ps_lift, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_quality, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_conjugate, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_misalign, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_memory, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_asymptotic, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_smooth, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_serfling, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_ball, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_binned, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_length, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_family, m)?)?;
    m.add_function(wrap_pyfunction!(eur::eur_secret, m)?)?;
    m.add_function(wrap_pyfunction!(cascade::cascade_run, m)?)?;
    m.add_function(wrap_pyfunction!(cascade::cascade_replay, m)?)?;

    Ok(())
}
